services:
  db:
    image: postgres:15-alpine
    container_name: asistencia_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asistencia_db
    ports:
      - "5435:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: asistencia_api
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=asistencia_db
      - DB_PASSWORD=password
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      - db

volumes:
  postgres_data:
